/* ============================================================
   Morning briefing, inbox and the day plan
   ============================================================ */

const DAY_PLANS = [
{
  day:1,
  headline:"Your second week. The ISMS is a blank Confluence page and a folder called 'security stuff (old)'.",
  standing:"Priya has two days a week and is using one of them today. Nobody has asked you to prove anything yet. That changes around Thursday.",
  tasks:["risk-metabase","sup-lumen"],
  inbox:[
    { id:"i-priya", src:"Email", from:"Priya Raghavan", subject:"Metabase thread — register entry by end of day",
      preview:"Forwarding you something Saskia picked up yesterday. I want it in the register as R-005 tonight, written properly. Read the whole thread before you start.",
      trueRank:1, taskId:"risk-metabase",
      why:"Not because the register entry is urgent — it isn't, it's due at 6pm. Because the thread contains a credential being handed round the company this morning, and Callum asked for it at 08:04. The ten-minute action lives inside the low-urgency task, and triage is how you find it." },
    { id:"i-drive", src:"Platform alert", from:"Google Workspace", subject:"Sharing summary — 'Termly Exports' shared drive",
      preview:"3 new link-sharing events in the last 7 days. 1 folder is shared with 'Anyone with the link'. This is a weekly digest; configure or mute in Admin settings.",
      trueRank:2,
      why:"The quietest thing in your inbox and potentially the largest exposure in the building. Automated digests are where real findings hide, precisely because they look like noise. Ten minutes to look, today." },
    { id:"i-nadia", src:"Email", from:"Nadia Haq", subject:"FW: Brightpath security questionnaire — Lumen Learning Analytics Ltd",
      preview:"Finally. Three chases and a phone call. I've held the PO. Product want them live for the summer release, which is six weeks away. Tell me what you need.",
      trueRank:3, taskId:"sup-lumen",
      why:"Nadia has waited three weeks and is holding a purchase order on your say-so. The PO means nothing is moving — but the six-week release date means every day you sit on it removes an option from the table." },
    { id:"i-bex", src:"Slack DM", from:"Bex Turner", subject:"Quick one — school wants a pupil's record deleted?",
      preview:"Marlbrook have emailed asking us to delete a Year 6 pupil's record entirely, the family have moved abroad. Do I just do it? Is there a form? Sorry if this is obvious 🙈",
      trueRank:4,
      why:"Four minutes of your time and it unblocks someone. It is also a controller instruction under Article 28(3)(e), which has its own clock, and Bex asking rather than guessing is a behaviour you want to reward within the hour." },
    { id:"i-callum", src:"Email", from:"Callum Wright", subject:"URGENT — Fenwick security schedule, need answers by 4pm",
      preview:"61 questions. I've done the easy ones. Need you on 12 to 31 (all the technical ones) by 4pm today so I can get it back to them. This is the whole deal Alex 🙏",
      trueRank:5,
      why:"Loud, capitalised, and not actually today's deadline — Fenwick asked for Friday and Callum has invented 4pm to create urgency. It gets done today. It does not get done first, and you should tell him the real date rather than absorbing the fake one." },
    { id:"i-tom", src:"Calendar", from:"Tom Whitlock", subject:"Invite: Kestrel catch-up — \"10 mins on where we are with ISO\" (Thursday 11:00)",
      preview:"Our operating partner at Kestrel is in on Thursday. Would be great if you could give a quick honest update on the certification timeline. Nothing formal!",
      trueRank:6,
      why:"Thursday, and \"nothing formal\" in front of an investor is never nothing formal. It needs twenty focused minutes before Wednesday evening. It does not need them now." },
    { id:"i-jira", src:"Ticket", from:"Jira — SEC board", subject:"SEC-14: Create ISMS documentation template in Confluence",
      preview:"Assigned to you by Rob Feeney. Priority: Medium. 'So we've got somewhere to put the policies when we write them.'",
      trueRank:7,
      why:"Real work, zero decay. It will be exactly as valuable on Friday as it is now, and nothing else in this list will be." }
  ],
  triageChecks:[
    { id:"t_live", dim:"judgement", w:3, label:"Found the live exposure inside the Metabase thread rather than treating it as an end-of-day writing task",
      any:[/callum|08:04|this morning|still (being )?(shared|handed|circulat)|stop|shut|kill|revoke|now|ongoing|live|before (i|anything)|spreading|five minutes|ten minutes/i] },
    { id:"t_quiet", dim:"judgement", w:3, label:"Did not dismiss the Workspace digest as noise",
      any:[/drive|sharing|workspace|digest|anyone with the link|link[- ]shar|alert|quiet|looks like noise|automated|exports/i] },
    { id:"t_fake", dim:"judgement", w:2, label:"Recognised Callum's 4pm as manufactured and handled it rather than obeying it",
      any:[/callum|4 ?pm|manufact|not (really|actually) |invented|real deadline|friday|push back|tell him|artificial|loud|urgen(t|cy) (is not|≠|does not)|61 questions/i] },
    { id:"t_cheap", dim:"craft", w:2, label:"Cleared the four-minute item early instead of letting it sit behind the big ones",
      any:[/bex|four minutes|quick|cheap|unblock|small|takes (a |two |five )?minute|out of the way|reply (first|early)|fast/i] },
    { id:"t_reason", dim:"communication", w:2, label:"Ordered by consequence and decay, not by who shouted loudest",
      any:[/consequence|decay|irreversib|can wait|gets worse|time[- ]critical|impact|reversib|will still be|tomorrow|no (decay|urgency)|loudest|volume|shout/i] },
    { id:"t_own", dim:"craft", w:1, label:"Said what you would drop or delegate if the day went wrong",
      any:[/if |drop|defer|move|tomorrow|delegate|ask (rob|nadia|bex|priya)|slip|renegotiat|tell (priya|tom|callum)|reschedul|protect/i] }
  ]
},
{
  day:2,
  headline:"Tuesday. Nothing on the calendar, which lasts until 09:41.",
  standing:"Priya read last night's register entry. She replied with one word: 'Better.' You are choosing to take that as praise.",
  tasks:["inc-export","sup-snapdesk"],
  inbox:[
    { id:"i2-bex", src:"Slack DM", from:"Bex Turner", subject:"Alex — I think I've done something bad",
      preview:"Or the mail merge has. Can you look now? Sanjay at Holt Green just replied saying \"this isn't ours\"…",
      trueRank:1, taskId:"inc-export",
      why:"Everything else in this list moved to tomorrow the moment you read the second sentence. Re-triage is not a failure of your plan; refusing to re-triage is." },
    { id:"i2-nadia", src:"Email", from:"Nadia Haq", subject:"Snapdesk — room booking. Please don't make this hard.",
      preview:"£41 a month. Four meeting rooms and a spreadsheet, and the spreadsheet has now caused two arguments and a missed board call…",
      trueRank:2, taskId:"sup-snapdesk",
      why:"Twenty minutes, and the relationship value is far higher than the security value. Nadia is the person who will tell you about every other tool this company buys — if you are quick and proportionate here." },
    { id:"i2-callum", src:"Email", from:"Callum Wright", subject:"Fenwick came back on Q14 (backups)",
      preview:"They've asked for 'evidence of the most recent successful restoration test'. Rob says just send the same answer again. Can you confirm?",
      trueRank:3,
      why:"A prospect has asked a question whose honest answer is 'we haven't done one'. It is not urgent today, but it must not be answered dishonestly while you are busy, so it needs a holding reply from you rather than silence." },
    { id:"i2-ellie", src:"Email", from:"Dr Ellie Mensah", subject:"pastoral_notes — can we talk about what's in it",
      preview:"I pulled a sample. Some of it should never have been a free-text field. I'd like ten minutes with you before I raise it with Saskia.",
      trueRank:4,
      why:"Your best ally in the building is offering you the inside track on a product design problem before it becomes an argument. Today if you can; this week regardless." },
    { id:"i2-hr", src:"Platform alert", from:"HiBob", subject:"Leaver processed: Marcus Elliot (Data Contractor) — last day 30 September",
      preview:"Offboarding checklist: 2 of 9 items complete. Outstanding: system access revocation (unassigned).",
      trueRank:5,
      why:"Backdated three and a half months and still unassigned — which tells you the leaver process does not work, which is a register entry, not an email. Note it, do not chase it today." },
    { id:"i2-tom", src:"Slack DM", from:"Tom Whitlock", subject:"how did thursday go / are we ok",
      preview:"sorry to be that guy. just want to know if there's anything I should be worrying about before I speak to Kestrel 🙏",
      trueRank:6,
      why:"Ninety seconds. Answer it honestly and briefly. An anxious CEO who is not updated becomes an anxious CEO who improvises." }
  ],
  triageChecks:[
    { id:"t_retriage", dim:"judgement", w:3, label:"Re-prioritised around the incident without apologising for the plan you lost",
      any:[/incident|bex|everything else|drop|re-?prior|re-?triage|first|now|immediate|stops|clears the day|moved|tomorrow/i] },
    { id:"t_holding", dim:"craft", w:2, label:"Protected the Fenwick answer from being sent dishonestly while you were busy",
      any:[/callum|holding (reply|response)|don'?t send|hold|two lines|tell him to wait|not (accurate|true)|restoration|stop him|before he/i] },
    { id:"t_cheap", dim:"craft", w:2, label:"Kept the twenty-minute supplier decision moving rather than letting it die behind the incident",
      any:[/nadia|snapdesk|twenty minutes|20 minutes|quick|still|today|later|don'?t (drop|lose)|end of day|squeeze/i] },
    { id:"t_leaver", dim:"judgement", w:2, label:"Read the HiBob alert as evidence of a broken process, not as a task",
      any:[/leaver|offboard|process|systemic|pattern|register|risk|unassigned|three months|backdat|symptom|not (just )?one/i] },
    { id:"t_tom", dim:"stake", w:1, label:"Gave the anxious CEO ninety seconds rather than nothing",
      any:[/tom|ninety|90 seconds|quick reply|brief|honest|reassur|short|one line|answer him/i] }
  ]
},
{
  day:3,
  headline:"Wednesday. Six schools have your incident reference and two have asked follow-up questions.",
  standing:"Priya told Tom, in front of you, that yesterday was handled 'about as well as it could have been'. Then she asked when the restore test is.",
  tasks:["risk-backup","sup-cloudspan"],
  inbox:[
    { id:"i3-callum", src:"Email", from:"Callum Wright", subject:"Re: Fenwick security schedule — question 14 (backup and recovery)",
      preview:"Rob says 'backups are on'. I'm about to send 'daily encrypted backups with point-in-time recovery'. Anything I should be worried about?",
      trueRank:2, taskId:"risk-backup",
      why:"He is about to send something to a prospect that omits the half of the question he cannot answer. The window in which that is cheap to fix is measured in hours." },
    { id:"i3-nadia", src:"Email", from:"Nadia Haq", subject:"Cloudspan — they've sent a SOC 2 instead",
      preview:"Their AM says 'we don't complete questionnaires, this satisfies all our enterprise customers'. Renewal is 28 February and they've gone up 18%.",
      trueRank:3, taskId:"sup-cloudspan",
      why:"Six weeks to renewal is exactly the right distance: close enough that your findings can change the contract, far enough that you are not negotiating under a deadline." },
    { id:"i3-school", src:"Email", from:"Priory Fields Academy — DPO", subject:"Incident ref BP-2026-002 — further questions",
      preview:"Thank you for yesterday's notification. Before we complete our own assessment we need to know: (1) whether pastoral_notes was populated for our cohort…",
      trueRank:1,
      why:"A controller cannot complete a 72-hour assessment without facts only you hold. Their clock is running and you are the delay. This is not customer service, it is an Article 28(3)(f) obligation with a deadline attached." },
    { id:"i3-rob", src:"Slack DM", from:"Rob Feeney", subject:"can you sign off the drive folder fix",
      preview:"Moved the exports to a service account, killed all link sharing, merge script now uses a scoped key. Screenshot attached. Can I close SEC-19?",
      trueRank:4,
      why:"Rob has done the work and wants closure. Look at what the screenshot actually evidences before you close anything — a screenshot with no date and no context is the exact habit you are here to break." },
    { id:"i3-gemma", src:"Slack", from:"Gemma Osei-Bonsu", subject:"the saved reply thing",
      preview:"Fine. You were right. I've rewritten it and I want you to check it before it goes live because if this makes tickets worse I'm coming for you.",
      trueRank:5,
      why:"A sceptic doing the thing you asked, voluntarily, and inviting you in. Ten minutes, and it is worth more to your next twelve months here than anything else on this list except the DPO." },
    { id:"i3-linked", src:"Platform alert", from:"LinkedIn", subject:"Rob Feeney updated his profile",
      preview:"'Open to opportunities'. 3 mutual connections also viewed this profile.",
      trueRank:6,
      why:"Not your business, not your inbox, and not nothing. The man holds root on the AWS account and is the single point of failure in R-003. File it, and let it sharpen how you write that entry." }
  ],
  triageChecks:[
    { id:"t_dpo", dim:"judgement", w:3, label:"Put the controller's questions first — their statutory clock is running on your answer",
      any:[/dpo|priory|controller|72|clock|their (deadline|assessment|obligation)|28\(3\)|statutory|blocking them|first/i] },
    { id:"t_callum", dim:"judgement", w:2, label:"Caught Callum before the answer went out rather than after",
      any:[/callum|before (he|it)|about to send|stop|intercept|hours|window|cheap|catch|q14|question 14/i] },
    { id:"t_evidence", dim:"craft", w:2, label:"Did not treat Rob's screenshot as closure",
      any:[/screenshot|evidence|no date|verify|check|independ|before (i|you) close|what does it (show|prove)|context|actually|myself/i] },
    { id:"t_gemma", dim:"stake", w:2, label:"Recognised what Gemma coming round is worth and spent the ten minutes",
      any:[/gemma|ten minutes|relationship|sceptic|came round|invest|worth|reinforce|reward|encourag|say yes/i] },
    { id:"t_rob", dim:"judgement", w:1, label:"Handled the LinkedIn item with some judgement — neither ignored nor acted on",
      any:[/linkedin|rob|r-?003|key ?person|single point|file it|not (my|our) business|note|register|discreet|don'?t (act|raise it with him)/i] }
  ]
},
{
  day:4,
  headline:"Thursday. Kestrel's operating partner is in the building at 11:00.",
  standing:"You have ten minutes with an investor, an infostealer, and a product decision that Ellie has been waiting two days for.",
  tasks:["inc-laptop","risk-intercom"],
  inbox:[
    { id:"i4-rob", src:"Slack", from:"Rob Feeney", subject:"Defender flagged and quarantined something on Dmitri's MacBook",
      preview:"Infostealer, AMOS family. He installed a 'free' Figma plugin from a Discord link on Tuesday night. It ran before it was stopped.",
      trueRank:1, taskId:"inc-laptop",
      why:"It executed, it touched the keychain, and something went out. Rob plans to reimage this afternoon, which destroys the evidence — so this is first for a reason that has nothing to do with how serious it turns out to be." },
    { id:"i4-ellie", src:"Slack", from:"Dr Ellie Mensah", subject:"the Intercom thing — I need it written down",
      preview:"I sat with Bex to watch how schools actually raise tickets. Gemma is going to push back. I'd rather you wrote it than me.",
      trueRank:3, taskId:"risk-intercom",
      why:"Ellie has waited two days and is about to have an argument with Gemma either way. Your entry decides whether that argument happens over evidence or over adrenaline." },
    { id:"i4-tom", src:"Calendar", from:"Tom Whitlock", subject:"Kestrel catch-up — 11:00 today, you're on at 11:20",
      preview:"Just be honest about where we are. Ludo is ex-operator, he'll smell it if we oversell.",
      trueRank:2,
      why:"Fixed time, cannot be moved, and twenty minutes of preparation changes the outcome completely. Immovable beats important: schedule around it first, then fill the gaps." },
    { id:"i4-callum", src:"Slack DM", from:"Callum Wright", subject:"the malware thing",
      preview:"Can we just not make a paper trail for something that got blocked? Fenwick's due diligence is in three weeks.",
      trueRank:4,
      why:"You will answer this inside the incident itself. It is on the list because you must not let it sit unanswered — silence reads as agreement, and Callum will tell someone you were fine with it." },
    { id:"i4-ico", src:"Email", from:"ICO — Casework", subject:"Correspondence ref IC-4471029: information request",
      preview:"We have received a complaint relating to Marlbrook Primary School. As a processor acting on behalf of the school, you may be asked to assist…",
      trueRank:5,
      why:"An ICO envelope raises everyone's heart rate, which is exactly why you read it properly before reacting. It is addressed to a controller matter, it asks nothing of you yet, and it has a response window measured in weeks — but Priya and Tom hear about it today, not next week." },
    { id:"i4-nadia", src:"Email", from:"Nadia Haq", subject:"Snapdesk is live, thank you",
      preview:"Founder signed the short-form DPA and the notification clause without blinking. He's sent the NHS correspondence too. Told everyone security isn't the enemy 🙂",
      trueRank:6,
      why:"Nothing to do. Read it, notice what it cost you, and notice what it bought." }
  ],
  triageChecks:[
    { id:"t_evidence", dim:"craft", w:3, label:"Stopped the reimage — the irreversible step is what makes the malware item first",
      any:[/reimage|wipe|irreversib|evidence|disk|image|before (he|rob)|stop|hold|preserve|this afternoon|destroy/i] },
    { id:"t_fixed", dim:"judgement", w:2, label:"Built the day around the immovable 11:00 rather than hoping to reach it",
      any:[/11|fixed|immovab|cannot (be )?move|calendar|around|prepar|before 11|schedule|anchor|slot/i] },
    { id:"t_ico", dim:"judgement", w:3, label:"Read the ICO letter calmly and correctly — it is a controller matter, it asks nothing yet, and it is still escalated today",
      any:[/controller|marlbrook|school|processor|assist|no (deadline|action) (yet|required)|read it|calm|don'?t panic|weeks|tell (priya|tom)|escalat|inform/i],
      penaltyAny:[/drop everything|panic|first thing|top priority|most (urgent|important)|before (anything|everything)/i] },
    { id:"t_callum", dim:"stake", w:2, label:"Did not let Callum's suggestion sit unanswered",
      any:[/callum|answer|reply|silence|unanswered|address it|same day|say no|not (ignore|leave)/i] },
    { id:"t_ellie", dim:"stake", w:1, label:"Gave Ellie a time rather than leaving her waiting a third day",
      any:[/ellie|tell her|by \d|this afternoon|today|time|commit|four|after|promise|won'?t slip/i] }
  ]
}
];

function planForDay(day){ return DAY_PLANS[(day-1) % DAY_PLANS.length]; }
